airline/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("flight.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flight/urls.py
from django.urls import path
from . import views

# Create your urlpatterns here.
urlpatterns = [
    path("", views.home_view, name="home"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),

    path("flight/", views.flight_view, name="flight"),
    path("client/", views.clients_view, name="client"),
    path("client/<str:pk>/", views.client_detail_view, name="client_detail"),
    path("passenger/<str:pk>/", views.passenger_view, name="passenger"),

    path("booking/<str:pk>/", views.update_flight_view, name="update-flight"),
    path("add_airport/", views.add_airport, name="add-airport"),
    path("book_flight/", views.booking_view, name="book-flight"),
    path("profile/", views.profile_view, name="profile"),


    path("untracked/", views.untracked_flight_view, name="untracked"),
]

flight/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

# Create your models here.

# ======================================================================================================
# THE CUSTOM USER MODEL MANAGER.
# ======================================================================================================

class CustomUserManager(BaseUserManager):
    def create_user(self, name, email, phone, photo, password=None):
        if not email:
            raise ValueError("User must have an email.")
        email = self.normalize_email(email)
        user = self.model(name=name, email=email, phone=phone, photo=photo)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, name, email, phone, password):
        user = self.create_user(name, email, phone, password)
        user.is_staff = True
        user.is_superuser = False
        user.save(using=self._db)
        return user

    def create_superuser(self, name, email, phone, password):
        user = self.create_user(name, email, phone, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

# ======================================================================================================
# THE CUSTOM USER THAT ALLOWS TO ADD MORE FIELDS THAN THE DEFAULT.
# ======================================================================================================

class CustomUser(AbstractUser):
    username = None
    name = models.CharField(max_length=64)
    photo = models.ImageField(upload_to="profile", default=None)
    email = models.EmailField(unique=True, max_length=64)
    phone = models.CharField(max_length=14)
    password = models.CharField(max_length=16)
    confirm_password = models.CharField(max_length=16)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["name", "phone"]

    class Meta:
        ordering = ["-created", "-updated"]

    def get_first_name(self):
        _name = self.name.split(" ")
        first_name = _name[0]
        return first_name

    def __str__(self):
        return self.get_first_name()

# ======================================================================================================
# THE PROFILE MODEL HANDLER FOR THE USER.
# ======================================================================================================

class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    email = models.EmailField(max_length=64)
    phone = models.CharField(max_length=14)
    photo = models.ImageField()

    def __str__(self):
        return self.name


# ======================================================================================================
# THE DATA THAT CONCERNS THE STAFF ONLY.
# ======================================================================================================

class Airport(models.Model):
    """AIRPORT FIELDS THAT THE STAFFS WILL FILL TO MAKE THE DATAS AVAILABLE FOR THE USERS CONVINENCE"""
    country = models.CharField(max_length=64)
    city = models.CharField(max_length=64)
    name = models.CharField(max_length=64)
    code = models.CharField(max_length=3)

    def __str__(self):
        return f"{ self.name }({ self.code }) of { self.city }"

FLIGHT_STATUS = (
    ("P", "Pending"),
    ("D", "Departed"),
    ("A", "Arrived"),
    ("C", "Cancelled"),
)

class Flight(models.Model):
    """FLIGHT FIELDS THAT THE STAFFS WILL FILL TO MAKE THE DATAS AVAILABLE FOR THE USERS CONVINENCE"""
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="initial")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="final")
    duration = models.IntegerField(blank=True, null=True)
    flight_status = models.CharField(choices=FLIGHT_STATUS, max_length=1, blank=True, null=True)

    def __str__(self):
        return f"Flight { self.id }: From { self.origin } to { self.destination }"

# ======================================================================================================
# THE DATA THAT CONCERNS THE USERS ALONE.
# ======================================================================================================

FLIGHT_TYPE = (
    ("B", "Business"),
    ("F", "First Class"),
    ("E", "Economy"),
    ("BE", "Business Economy"),
)

class Passenger(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="user")
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departure")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrival")
    # flight = models.ManyToManyField(Flight, blank=True, related_name="passenger")
    flight_class = models.CharField(choices=FLIGHT_TYPE, max_length=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.name

flight/forms.py
from django import forms
from .models import Airport, Flight, Passenger, Profile

# Create your forms here.
class CustomUserForm(forms.Form):
    name = forms.CharField(max_length=64)
    email = forms.EmailField(max_length=64)
    phone = forms.CharField(max_length=14)
    photo = forms.ImageField()
    password = forms.CharField(min_length=8, max_length=16, widget=forms.PasswordInput)
    confirm_password = forms.CharField(min_length=8, max_length=16, widget=forms.PasswordInput)
    

class AirportForm(forms.ModelForm):
    class Meta:
        model = Airport
        fields = "__all__"

class FlightForm(forms.ModelForm):
    class Meta:
        model = Flight
        fields = "__all__"

class PassengerForm(forms.ModelForm):
    class Meta:
        model = Passenger
        fields = "__all__"
        exclude = ("user",)

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"
        exclude = ("user",)

flight/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from .models import Airport, CustomUser, Flight, Flight, Passenger, Profile
from .forms import AirportForm, CustomUserForm, PassengerForm, FlightForm, FlightForm
from django.shortcuts import render, redirect
from .decorators import restriction
from django.contrib import messages

# Create your views here.
def home_view(request, *args, **kwargs):
    return render(request, "home.html")

@restriction
def register_view(request, *args, **kwargs):
    form = CustomUserForm()
    if request.method == "POST":

        form = CustomUserForm(request.POST, request.FILES)

        if form.is_valid():

            name = form.cleaned_data.get("name")
            email = form.cleaned_data.get("email")
            phone = form.cleaned_data.get("phone")
            photo = form.cleaned_data.get("phote")
            password = form.cleaned_data.get("password")
            confirm_password = form.cleaned_data.get("confirm_password")
        
            if password != confirm_password:
                messages.error(request, "ERROR: Your password didn't match.")
                return redirect("register")
            if CustomUser.objects.filter(email=email).exists():
                messages.error(request, "ERROR: Email already taken.")
                return redirect("register")
            elif CustomUser.objects.filter(phone=phone).exists():
                messages.error(request, "ERROR: Phone number already used.")
                return redirect("register")
            else:
                user = CustomUser.objects.create_user(name=name, email=email, phone=phone, password=password, photo=photo)
                user.save()
                login(request, user)
                messages.success(request, "Registration successful...")
                return redirect("home")
    # if request.method == "POST":
    #     name = request.POST["name"]
    #     email = request.POST["email"]
    #     phone = request.POST["phone"]
    #     password = request.POST["password"]
    #     confirm_password = request.POST["confirm_password"]
    #     # photo = request.POST["photo"]
    #     if password != confirm_password:
    #         messages.error(request, "Password did not match...")
    #         return redirect("register")
    #     elif CustomUser.objects.filter(email=email).exists():
    #         messages.info(request, "Email already taken...")
    #         return redirect("register")
    #     elif CustomUser.objects.filter(phone=phone).exists():
    #         messages.info(request, "Phone number already taken...")
    #         return redirect("register")
    #     else:
    #         user = CustomUser.objects.create_user(name=name, email=email, phone=phone, password=password)
    #         user.save()
    #         login(request, user)
    #         messages.success(request, "Registration successful...")
    #         return redirect("home")
    return render(request, "register.html", { "form": form })

@restriction
def login_view(request, *args, **kwargs):
    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]
        try:
            user = CustomUser.objects.get(email=email)
        except:
            messages.error(request, "User does not have an account with us...")
            return redirect("login")
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Login successful...")
            return redirect("home")
        else:
            messages.error(request, "User is None(AnonymousUser)...")
            return redirect("login")
    return render(request, "login.html")

@login_required(login_url="login")
def logout_view(request, *args, **kwargs):
    logout(request)
    messages.success(request, "Logged Out...")
    return redirect("home")

@login_required(login_url="login")
def flight_view(request, *args, **kwargs):
    flights = Flight.objects.all()
    context = {"flights": flights}
    return render(request, "flight.html", context)

@login_required(login_url="login")
def clients_view(request, *args, **kwargs):
    clients = Passenger.objects.all()
    context = { "clients": clients }
    return render(request, "client.html", context)

@login_required(login_url="login")
def client_detail_view(request, pk, *args, **kwargs):
    clients = Passenger.objects.get(id=pk)
    flights = clients.flight.all()
    context = { "clients": clients, "flights": flights }
    return render(request, "client_detail.html", context)

@login_required(login_url="login")
def passenger_view(request, pk, *args, **kwargs):
    flight = Flight.objects.get(id=pk)
    passengers = Passenger.objects.filter(origin=flight.origin, destination=flight.destination)
    context = { "passengers": passengers, "flight": flight }
    return render(request, "passenger.html", context)

@login_required(login_url="login")
def untracked_flight_view(request, *args, **kwargs):
    flights = Flight.objects.filter(flight_status=None)
    context = { "flights": flights }
    return render(request, "untracked_flight.html", context)

@login_required(login_url="login")
def update_flight_view(request, pk, *args, **kwargs):
    data = Flight.objects.get(id=pk)
    form = FlightForm(instance=data)
    if request.method == "POST":
        form = FlightForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            messages.success(request, "Flight track successfully...")
            return redirect("home")
        else:
            messages.error(request, "Flight track was not successful...")
            return redirect("update-flight")
    context = { "form": form }
    return render(request, "update_flight.html", context)

@login_required(login_url="login")
def add_airport(request, *args, **kwargs):
    form = AirportForm()
    if request.method == "POST":
        form = AirportForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Added new Airport...")
            return redirect("add-airport")
        else:
            messages.error(request, "Invalid Form Entry...")
            return redirect("add-airport")
    context = { "form": form }
    return render(request, "create_airport.html", context)

@login_required(login_url="login")
def booking_view(request, *args, **kwargs):
    form = PassengerForm()
    if request.method == "POST":
        form = PassengerForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.user = request.user
            user.save()
            flight = Flight.objects.create(origin=user.origin, destination=user.destination)
            flight.save()
            messages.success(request, "Flight Booked successfully...")
            return redirect("home")
        else:
            messages.error(request, "Invalid Form Entry...")
            return redirect("book-flight")
    context = { "form": form }
    return render(request, "book_flight.html", context)

@login_required(login_url="login")
def profile_view(request, *args, **kwargs):
    profile = Profile.objects.get(user=request.user)
    context = { "profile": profile }
    return render(request, "profile.html", context)

flight/templates/book_flight.html
{% extends "main.html" %}

{% block content %}

<div>
    <form method="post" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Book">
        <a href="{{ request.META.HTTP_REFERER }}">Cancel</a>
    </form>
</div>

{% endblock content %}

flight/templates/client.html
{% extends "main.html" %}

{% block content %}

<div class="">
  <ul>
    {% for client in clients %}
      <li><a href="{% url 'client_detail' client.id %}">{{ client }}</a></li>
    {% endfor %}
  </ul>
</div>

{% endblock content %}

flight/templates/client_detail.html
{% extends "main.html" %}

{% block content %}

<div class="">
  <p>Name: {{ clients.user.name|title }}</p>
  <p>Email address: {{ clients.user.email }}</p>
  <p>Flight class: {{ clients.get_flight_type_display }}</p>

  {% for flight in flights %}
    <p>Flight: {{ flight }}.</p>
    <p>Flight status: {{ flight.get_flight_status_display }}</p>
  {% endfor %}
</div>

{% endblock content %}

flight/templates/create_airport.html
{% extends "main.html" %}

{% block content %}

<div>
    <form method="post" autocomplete="off" autocapitalize="on">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
        <a href="{{ request.META.HTTP_REFERER }}">Cancel</a>
    </form>
</div>

{% endblock content %}

flight/templates/flight.html
{% extends "main.html" %}

{% block content %}

<div class="">

  <ul>
    {% for flight in flights %}
      <li><a href="{% url 'passenger' flight.id %}">{{ flight }}</a></li>
    {% endfor %}
  </ul>

</div>

{% endblock content %}

flight/templates/home.html
{% extends "main.html" %}

{% block content %}

  <div class="">
    <h3>home page content</h3>
  </div>

{% endblock content %}

flight/templates/login.html
{% extends "main.html" %}

{% block content %}

<div class="">
  <form method="post" autocomplete="off">
    {% csrf_token %}
    <input type="email" name="email" placeholder="Email address">
    <input type="password" name="password" placeholder="Password">
    <input type="submit" value="Login">
  </form>
  <p>Don't have an account yet? <a href="{% url 'register' %}">Register</a></p>
</div>

{% endblock content %}

flight/templates/passenger.html
{% extends "main.html" %}

{% block content %}

<div class="">
  <ul>
    {% for passenger in passengers %}
     <li><a href="{% url 'client_detail' passenger.id %}">{{ passenger }}</a></li>
     <li>{{ passenger.get_flight_class_display }}</li>
    {% endfor %}
    <li>{{ flight.get_flight_status_display }}</li>
  </ul>

</div>

{% endblock content %}

flight/templates/profile.html
{% extends "main.html" %}

{% block content %}

<div>
    <div id="profile-photo"><img src="{{ profile.photo.url }}"></div>
    {{ profile.name }}
    {{ profile.email }}
    {{ profile.phone }}
    <!-- TODO: Add other informations about the user to the page. -->
</div>

{% endblock content %}

flight/templates/register.html
{% extends "main.html" %}

{% block content %}

  <div class="">
    <form method="post" autocomplete="off" enctype="multipart/form-data">
      {% csrf_token %}

      {{ form.as_p }}
      <!-- <input type="text" name="name" placeholder="Full name">
      <input type="email" name="email" placeholder="Email address">
      <input type="text" name="phone" placeholder="Phone number">
      <input type="password" name="password" placeholder="Password">
      <input type="password" name="confirm_password" placeholder="Confirm password"> -->
      <!-- <input type="file" name="photo" required> -->
      <input type="submit" value="Register">
    </form>
    <p>You already have an account? <a href="{% url 'login' %}">Login</a></p>
  </div>

{% endblock content %}

flight/templates/untracked_flight.html
{% extends "main.html" %}

{% block content %}

<div>
    {% for flight in flights %}
        <a href="{% url 'update-flight' flight.id %}">{{ flight }}</a>
    {% endfor %}
</div>

{% endblock content %}

flight/templates/update_flight.html
{% extends "main.html" %}

{% block content %}

<div>
    <form method="post" autocomplete="off">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{{ request.META.HTTP_REFERER }}">Cancel</a>
        <input type="submit" value="Update">
    </form>
</div>

{% endblock content %}